version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql-container
    networks:
      - mynetwork

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork:
